@include('header')
<div style="padding:30px 0px;border-top:1.25px solid rgb(233, 233, 233);background:rgb(248, 249, 249) none repeat scroll 0% 0% / auto padding-box border-box;border-bottom:1.25px solid rgb(233, 233, 233);box-sizing:border-box;">
    <div style="width: 1140px;max-width:100%;padding-right:15px;padding-left:15px;position:relative;margin-left: auto;margin-right: auto;box-sizing:border-box;">
        <h1 style="font-size:24px;margin-bottom:0px;font-weight:600;letter-spacing:1px;text-transform:uppercase;word-break:break-word;overflow-wrap:break-word;line-height:31.2px;clear:both;font-family:comforta_regular;margin-top:0px;color:rgb(51, 51, 51);box-sizing:border-box;margin:0px;">Appels d’offres</h1>
    </div>
</div>
<div style="border-top:1.25px solid rgb(233, 233, 233);margin-top:-1px;box-sizing:border-box;">
    <div style="width: 1140px;max-width:100%;padding-right:15px;padding-left:15px;position:relative;margin-left: auto;margin-right: auto;box-sizing:border-box;">
        <div style="padding-right:39px;border-right:1.25px solid rgb(233, 233, 233);width: 100%;float:left;padding-bottom:40px;padding-top:40px;box-sizing:border-box;">
            <main role="main" style="box-sizing:border-box;display:block;">



                <article style="box-sizing:border-box;display:block;">
                    <header style="box-sizing:border-box;display:block;">
                    </header><!-- .entry-header -->
                    <div style="margin-bottom:30px;box-sizing:border-box;counter-reset:footnotes 0;">
                        <div style="box-sizing:border-box;">
                            <div style="box-sizing:border-box;"></div>
                        </div>
                        <div style="box-sizing:border-box;">
                            <p style="text-align: justify;word-break:break-word;overflow-wrap:break-word;margin-bottom:15px;margin-top:0px;box-sizing:border-box;"><span style="font-family: comforta_regular;box-sizing:border-box;">Cette rubrique vous permet de consulter les informations relatives aux appels d’offres et consultations lancés par l’a Fondation et suivre leur état d’avancement depuis l’ouverture des plis jusqu’à l’attribution du marché.</span></p>
                        </div>
                        <div style="clear:both;margin-bottom:16px;position:relative;box-sizing:border-box;">
                            <div style="float:left;white-space:nowrap;box-sizing:border-box;"><label style="display:inline-block;margin-bottom:8px;touch-action:manipulation;box-sizing:border-box;">Afficher <select name="tablepress-2_length" aria-controls="tablepress-2" style="display:inline-block;margin:2px;width: auto;max-width:100%;overflow: auto;vertical-align:top;outline:rgb(119, 119, 119) none 0px;border:1.25px solid rgb(233, 233, 233);padding:10px;font-family:'Open Sans', Helvetica, Arial, sans-serif;font-size:14px;line-height:normal;color:rgb(119, 119, 119);touch-action:manipulation;box-sizing:border-box;text-transform:none;">
                                        <option value="10" style="box-sizing:content-box;">10</option>
                                        <option value="25" style="box-sizing:content-box;">25</option>
                                        <option value="50" style="box-sizing:content-box;">50</option>
                                        <option value="100" style="box-sizing:content-box;">100</option>
                                    </select> éléments</label></div>
                            <div style="float:right;white-space:nowrap;box-sizing:border-box;"><label style="display:inline-block;margin-bottom:8px;touch-action:manipulation;box-sizing:border-box;">Rechercher:<input type="search" placeholder="" aria-controls="tablepress-2" style="margin-left:7.5px;margin-right:0px;display:inline;width: auto;padding:10px;max-width:100%;border-width:0px 0px 1.25px;border-top-style:none;border-right-style:none;border-left-style:none;border-top-color:rgb(0, 0, 0);border-right-color:rgb(0, 0, 0);border-left-color:rgb(0, 0, 0);border-image:none;font-size:15px;font-weight:400;line-height:22px;box-shadow:rgba(0, 0, 0, 0.12) 0px 1px 2px 0px inset;transition:all 0.2s linear 0s;background-color:rgb(242, 242, 242);border-bottom-style:solid;border-bottom-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:'Open Sans', Helvetica, Arial, sans-serif;appearance:none;touch-action:manipulation;outline-offset:-2.01172px;overflow:visible;" /></label></div>
                            <table aria-describedby="tablepress-2_info" style="--head-active-bg-color: #c4c6c4;--head-active-text-color: #111;clear:both;margin-bottom:0px;--text-color: #111;--head-text-color: #111;--head-bg-color: #d9edf7;--odd-text-color: #111;--odd-bg-color: #f9f9f9;--even-text-color: #111;--even-bg-color: #fff;--hover-text-color: #111;--hover-bg-color: #f3f3f3;--border-color: #ddd;--padding: 0.5rem;border:0px none rgb(119, 119, 119);border-collapse:collapse;border-spacing:0px 0px;margin: 0px auto 1rem;table-layout: auto;width: 100%;margin-top:0px;background-color:rgba(0, 0, 0, 0);box-sizing:border-box;">
                                <thead style="box-sizing:border-box;">
                                    <tr style="box-sizing:border-box;">
                                        <th tabindex="0" aria-controls="tablepress-2" rowspan="1" colspan="1" aria-label="N°: activer pour trier la colonne par ordre croissant" style="width: 37.5195px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">N°</th>
                                        <th tabindex="0" aria-controls="tablepress-2" rowspan="1" colspan="1" aria-label="Date limite de dépôt des plis	: activer pour trier la colonne par ordre croissant" style="width: 113.613px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Date limite de dépôt des plis </th>
                                        <th tabindex="0" aria-controls="tablepress-2" rowspan="1" colspan="1" aria-label="Objet: activer pour trier la colonne par ordre croissant" style="width: 553.379px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Objet</th>
                                        <th tabindex="0" aria-controls="tablepress-2" rowspan="1" colspan="1" aria-label="Dossier de consultation: activer pour trier la colonne par ordre croissant" style="width: 136.523px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Dossier de consultation</th>
                                        <th tabindex="0" aria-controls="tablepress-2" rowspan="1" colspan="1" :="" activer="" pour="" trier="" la="" colonne="" par="" ordre="" style="width: 67.5px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Résultat<br style="box-sizing:content-box;" /> </th>
                                    </tr>
                                </thead>
                                <tbody style="box-sizing:border-box;">




                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">54/2023</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">11/09/2023</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">Achat de matériel réseau informatique pour la Fondation Mohammed VI de Promotion des Œuvres Sociales de l’Education-Formation.<br style="box-sizing:content-box;" /> <br style="box-sizing:content-box;" /> </td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">
                                            <div style="box-sizing:content-box;"><a 2023="" href="[pdf-embedder url=" https:="" maeci.ma="" wp="" wp-content="" uploads="" 05="" pages-12.16-bo_6749_ar-creation-fondation-2.pdf"="" title="Pages 12.16 BO_6749_Ar Création Fondation" ]"="" style="color:rgb(255, 255, 255);text-decoration:none solid rgb(255, 255, 255);outline:rgb(255, 255, 255) none 0px;touch-action:manipulation;box-sizing:border-box;background-color:rgb(50, 55, 60);border-radius:9999px;box-shadow:none;padding:12.5052px 22.9947px;cursor:pointer;display:inline-block;text-align:center;word-break:break-word;font-size:15.75px;">Telecharger</a></div>
                                        </td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">53/2023</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">11/09/2023</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">Maintenance préventive et curative relative aux équipements de climatisation et de surveillance environnementale des salles techniques de la Fondation Mohammed VI de Promotion des Œuvres Sociales de l’Education – Formation.<br style="box-sizing:content-box;" /> <br style="box-sizing:content-box;" /> </td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">
                                            <div style="box-sizing:content-box;"><a 2023="" href="[pdf-embedder url=" https:="" maeci.ma="" wp="" wp-content="" uploads="" 05="" pages-12.16-bo_6749_ar-creation-fondation-2.pdf"="" title="Pages 12.16 BO_6749_Ar Création Fondation" ]"="" style="color:rgb(255, 255, 255);text-decoration:none solid rgb(255, 255, 255);outline:rgb(255, 255, 255) none 0px;touch-action:manipulation;box-sizing:border-box;background-color:rgb(50, 55, 60);border-radius:9999px;box-shadow:none;padding:12.5052px 22.9947px;cursor:pointer;display:inline-block;text-align:center;word-break:break-word;font-size:15.75px;">Telecharger</a></div>
                                        </td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <div role="status" aria-live="polite" style="clear:both;float:left;margin:4px 0px 0px;box-sizing:border-box;">Affichage des éléments 1 à 4 sur 4 éléments</div>
                            <div style="padding:0px 15px;float:right;margin:4px 0px 0px;box-sizing:border-box;"><a aria-controls="tablepress-2" aria-disabled="true" role="link" data-dt-idx="previous" tabindex="-1" style="color:rgb(153, 153, 153);cursor:default;text-decoration:none solid rgb(153, 153, 153);margin-left:0px;display:inline-block;margin:0px 5px 0px 0px;outline:rgb(153, 153, 153) none 0px;position:relative;touch-action:manipulation;box-sizing:border-box;background-color:rgba(0, 0, 0, 0);">Précédent</a><a aria-controls="tablepress-2" aria-disabled="true" role="link" data-dt-idx="next" tabindex="-1" style="color:rgb(153, 153, 153);cursor:default;text-decoration:none solid rgb(153, 153, 153);margin-right:0px;display:inline-block;margin:0px 0px 0px 5px;outline:rgb(153, 153, 153) none 0px;position:relative;touch-action:manipulation;box-sizing:border-box;background-color:rgba(0, 0, 0, 0);">Suivant</a></div>
                        </div>
                    </div><!-- .entry-content -->
                </article><!-- #post-## -->
            </main><!-- #main -->
        </div><!-- #primary -->
        <!-- #secondary -->
    </div>
    <!--#content-inside -->
</div>