@include('header')
<div style="padding:30px 0px;border-top:1.25px solid rgb(233, 233, 233);background:rgb(248, 249, 249) none repeat scroll 0% 0% / auto padding-box border-box;border-bottom:1.25px solid rgb(233, 233, 233);box-sizing:border-box;">
    <div style="width: 1140px;max-width:100%;padding-right:15px;padding-left:15px;position:relative;margin-left: auto;margin-right: auto;box-sizing:border-box;">
        <h1 style="font-size:24px;margin-bottom:0px;font-weight:600;letter-spacing:1px;text-transform:uppercase;word-break:break-word;overflow-wrap:break-word;line-height:31.2px;clear:both;font-family:comforta_regular;margin-top:0px;color:rgb(51, 51, 51);box-sizing:border-box;margin:0px;">Offres d’emplois</h1>
    </div>
</div>
<div style="border-top:1.25px solid rgb(233, 233, 233);margin-top:-1px;box-sizing:border-box;">
    <div style="width: 1140px;max-width:100%;padding-right:15px;padding-left:15px;position:relative;margin-left: auto;margin-right: auto;box-sizing:border-box;">
        <div style="padding-right:39px;border-right:1.25px solid rgb(233, 233, 233);width: 100%;float:left;padding-bottom:40px;padding-top:40px;box-sizing:border-box;">
            <main role="main" style="box-sizing:border-box;display:block;">



                <article style="box-sizing:border-box;display:block;">
                    <header style="box-sizing:border-box;display:block;">
                    </header><!-- .entry-header -->
                    <div style="margin-bottom:30px;box-sizing:border-box;counter-reset:footnotes 0;">
                        <p style="word-break:break-word;overflow-wrap:break-word;margin-bottom:15px;margin-top:0px;box-sizing:border-box;"><span style="font-family: comforta_regular;box-sizing:border-box;">Cette rubrique vous permet de consulter les offres d’emplois lancées par la fondation</span></p>
                        <div style="clear:both;margin-bottom:16px;position:relative;box-sizing:border-box;">
                            <div style="float:left;white-space:nowrap;box-sizing:border-box;"><label style="display:inline-block;margin-bottom:8px;touch-action:manipulation;box-sizing:border-box;">Afficher <select name="tablepress-3_length" aria-controls="tablepress-3" style="display:inline-block;margin:2px;width: auto;max-width:100%;overflow: auto;vertical-align:top;outline:rgb(119, 119, 119) none 0px;border:1.25px solid rgb(233, 233, 233);padding:10px;font-family:'Open Sans', Helvetica, Arial, sans-serif;font-size:14px;line-height:normal;color:rgb(119, 119, 119);touch-action:manipulation;box-sizing:border-box;text-transform:none;">
                                        <option value="10" style="box-sizing:content-box;">10</option>
                                        <option value="25" style="box-sizing:content-box;">25</option>
                                        <option value="50" style="box-sizing:content-box;">50</option>
                                        <option value="100" style="box-sizing:content-box;">100</option>
                                    </select> éléments</label></div>
                            <div style="float:right;white-space:nowrap;box-sizing:border-box;"><label style="display:inline-block;margin-bottom:8px;touch-action:manipulation;box-sizing:border-box;">Rechercher:<input type="search" placeholder="" aria-controls="tablepress-3" style="margin-left:7.5px;margin-right:0px;display:inline;width: auto;padding:10px;max-width:100%;border-width:0px 0px 1.25px;border-top-style:none;border-right-style:none;border-left-style:none;border-top-color:rgb(0, 0, 0);border-right-color:rgb(0, 0, 0);border-left-color:rgb(0, 0, 0);border-image:none;font-size:15px;font-weight:400;line-height:22px;box-shadow:rgba(0, 0, 0, 0.12) 0px 1px 2px 0px inset;transition:all 0.2s linear 0s;background-color:rgb(242, 242, 242);border-bottom-style:solid;border-bottom-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:'Open Sans', Helvetica, Arial, sans-serif;appearance:none;touch-action:manipulation;outline-offset:-2.01172px;overflow:visible;" /></label></div>
                            <table aria-describedby="tablepress-3_info" style="--head-active-bg-color: #c4c6c4;--head-active-text-color: #111;clear:both;margin-bottom:0px;--text-color: #111;--head-text-color: #111;--head-bg-color: #d9edf7;--odd-text-color: #111;--odd-bg-color: #f9f9f9;--even-text-color: #111;--even-bg-color: #fff;--hover-text-color: #111;--hover-bg-color: #f3f3f3;--border-color: #ddd;--padding: 0.5rem;border:0px none rgb(119, 119, 119);border-collapse:collapse;border-spacing:0px 0px;margin: 0px auto 1rem;table-layout: auto;width: 100%;margin-top:0px;background-color:rgba(0, 0, 0, 0);box-sizing:border-box;">
                                <thead style="box-sizing:border-box;">
                                    <tr style="box-sizing:border-box;">
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Poste: activer pour trier la colonne par ordre croissant" style="width: 131.816px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Poste</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Dossier de candidature: activer pour trier la colonne par ordre croissant" style="width: 123.379px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Dossier de candidature</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Date de publication: activer pour trier la colonne par ordre croissant" style="width: 112.09px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Date de publication</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Fiche de poste	: activer pour trier la colonne par ordre croissant" style="width: 66.1133px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Fiche de poste </th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Date de soumission: activer pour trier la colonne par ordre croissant" style="width: 109.121px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Date de soumission</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Préselection: activer pour trier la colonne par ordre croissant" style="width: 104.492px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Préselection</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Réslutats: activer pour trier la colonne par ordre croissant" style="width: 77.1094px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Réslutats</th>
                                        <th tabindex="0" aria-controls="tablepress-3" rowspan="1" colspan="1" aria-label="Candidat retenu: activer pour trier la colonne par ordre croissant" style="width: 87.6758px;background:rgb(153, 40, 36) none repeat scroll 0% 0% / auto padding-box border-box;padding:10px 20px 10px 11px;font-size:10px;text-align:left;color:rgb(255, 255, 255);border-right:1.25px solid rgb(255, 255, 255);font-family:Comfortaa, cursive;cursor:pointer;outline:rgb(255, 255, 255) none 0px;padding-right:20px;position:relative;background-color:rgb(153, 40, 36);font-weight:700;vertical-align:middle;word-break:normal;border: none;box-sizing:content-box;float:none;letter-spacing:2px;text-transform:uppercase;border-bottom-width:0px;line-height:14.2857px;">Candidat retenu</th>
                                    </tr>
                                </thead>
                                <tbody style="box-sizing:border-box;">




                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">Chef de service Partenariats et Actions Sociales</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">16/05/2023</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">02/06/2023</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">Technicien en Bâtiments</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">08/05/2023</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">31/05/2023</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;">-</td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(255, 255, 255);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                    <tr style="box-sizing:border-box;">
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                        <td style="background-color:rgb(249, 249, 249);color:rgb(17, 17, 17);border-top:1.25px solid rgb(221, 221, 221);border: none;box-sizing:content-box;padding:8px;text-align:left;vertical-align:top;float:none;line-height:20px;"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <div role="status" aria-live="polite" style="clear:both;float:left;margin:4px 0px 0px;box-sizing:border-box;">Affichage des éléments 1 à 4 sur 4 éléments</div>
                            <div style="padding:0px 15px;float:right;margin:4px 0px 0px;box-sizing:border-box;"><a aria-controls="tablepress-3" aria-disabled="true" role="link" data-dt-idx="previous" tabindex="-1" style="color:rgb(153, 153, 153);cursor:default;text-decoration:none solid rgb(153, 153, 153);margin-left:0px;display:inline-block;margin:0px 5px 0px 0px;outline:rgb(153, 153, 153) none 0px;position:relative;touch-action:manipulation;box-sizing:border-box;background-color:rgba(0, 0, 0, 0);">Précédent</a><a aria-controls="tablepress-3" aria-disabled="true" role="link" data-dt-idx="next" tabindex="-1" style="color:rgb(153, 153, 153);cursor:default;text-decoration:none solid rgb(153, 153, 153);margin-right:0px;display:inline-block;margin:0px 0px 0px 5px;outline:rgb(153, 153, 153) none 0px;position:relative;touch-action:manipulation;box-sizing:border-box;background-color:rgba(0, 0, 0, 0);">Suivant</a></div>
                        </div> <!-- #tablepress-3 from cache -->
                    </div><!-- .entry-content -->
                </article><!-- #post-## -->
            </main><!-- #main -->
        </div><!-- #primary -->
        <!-- #secondary -->
    </div>
    <!--#content-inside -->
</div>